[WORLD]
NAME=P7K-135 Zigara
[THERMO]
THERMO=Warm
CR=0
Orbit=Varies
Temp=2d20+25 deg F
[ATMO]
ATMO=Normal
CR=0
PRESS=0.7-1.5 atm
PEN=None
INCREMENT=None
SAVE=None
DAM=None
TIME=None
[HYDRO]
HYDRO=Sub-Humid
RAIN=88-93 rain(1d4-1 in.) or snow (1d6-1 in.)
NONE=1-85
FLOOD=86-87 (1d10 mph)
STORM=94-95 thunderstorm or snowstorm 95 hurricane or blizzard
WIND=97-98 (1d10 mph) 99 (1d10+10 mph) 100 (1d10+20 mph)
[GEOB]
GEOB=Exotic
SPECIAL=See MRB Pg 445 For examples
[GEOT]
GEOT=Stable
QNONE=1-99
QMINOR=100
QMOD=N/A
QMAJ=N/A
VNONE=N/A
VSMALL=N/A(5%)
VMED=N/A
VLARGE=N/A
[BIO]
BIO=Wasteland
MOVE=Per Scrub
TEMP=+0 deg F(Summer), +0 deg F (Winter)
RAIN=+0%(Summer), +5% (Winter)
VEG=Devastated ecology
[SEASON]
SEASON=Mild
SPR=1-17
SPRT=Unchanged
SUM=18-50
SUMT=+2d10 DegF
AUT=51-83
AUTT=Unchanged
WIN=84-100
WINT=-2d10 DegF
[ANTHRO]
ANTHRO=Nuclear
ADV=Nuclear fission, television, radio, jet power, radar, sonar, computers
WEAPON=Machineguns, Atom bombs
VEHICLE=Airplanes, Jets
PICK=5
RP=4
[MILITARY]
MILITARY=Extremely Cautious
FORCE=1 Soldier per 50,000
SQUAD=1d4 Soldiers
COND=When their territory, people or property are attacked
[GOV]
GOV=Republic
RULER=One or more officials elected by the population, who in turn vote to establish policy
[XENO]
XENO=Suspicious
DISP=Unfriendly
MOD=-1
[CIVIL]
CIVIL=Moderate
SUB=Never (laws against slavery, but not against prejudice)
GENO=Never by the government, but some people may differ
[ORIA]
ORIA=Old
[ORIR]
ORIR=Assyrian
DESC=Messoptamia, Syria, - 1600BC => 609BC
[NOTE]
NOTE=
