[WORLD]
NAME=Vanaheim
[THERMO]
THERMO=Cold
CR=0
Orbit=Varies
Temp=-(1d%) deg F
[ATMO]
ATMO=Normal
CR=0
PRESS=0.7-1.5 atm
PEN=None
INCREMENT=None
SAVE=None
DAM=None
TIME=None
[HYDRO]
HYDRO=Humid
RAIN=83-91 rain(1d6 in.) or snow (1d10 in.)
NONE=1-79
FLOOD=80-81 (1d10 mph) 82 (1d10+10 mph)
STORM=92-96 thunderstorm or snowstorm 97-98 hurricane or blizzard
WIND=99 (1d10 mph) 100 (1d10+10 mph)
[GEOB]
GEOB=Mountains
SPECIAL=See MRB Pg 445
[GEOT]
GEOT=Stable
QNONE=1-99
QMINOR=100
QMOD=N/A
QMAJ=N/A
VNONE=N/A
VSMALL=N/A(5%)
VMED=N/A
VLARGE=N/A
[BIO]
BIO=C-M Forest
MOVE=Per Forest
TEMP=-10 deg F(Summer), +10 deg F (Winter)
RAIN=+0%(Summer), +10% (Winter)
VEG=Many trees, great ground foliage
[SEASON]
SEASON=Very Mild
SPR=1-42
SPRT=Unchanged
SUM=43-50
SUMT=+2d6 DegF
AUT=51-92
AUTT=Unchanged
WIN=93-100
WINT=-2d6 DegF
[ANTHRO]
ANTHRO=Eletronic
ADV=Orbital space flight, computers, organ transplants, lasers/masers, worldwide computer network, genome mapping, human/machine interface, cloning, sub-atomic particle teleportation
WEAPON=Grenade launchers, Kevlar
VEHICLE=Spaceships, Helecopters
PICK=6
RP=4
[MILITARY]
MILITARY=Sensitive
FORCE=1 Soldier per 50,000
SQUAD=1d4 Soldiers
COND=When their code of ethics is slightly offended
[GOV]
GOV=Stratocracy
RULER=One military group
[XENO]
XENO=Suspicious
DISP=Unfriendly
MOD=-1
[CIVIL]
CIVIL=Progressive
SUB=Never (laws against all prejudice, but their rarely enforced)
GENO=Never by the government or the people
[ORIA]
ORIA=Very Old
[ORIR]
ORIR=Norse
DESC=Scandinavia
[NOTE]
NOTE=
